[rewrite_local]
^https://fluxapi\.vvebo\.vip/v1/purchase/iap/subscription url script-analyze-echo-response https://mock.forward1.workers.dev/forward/qx-response.js

[mitm]
hostname = fluxapi.vvebo.vip
